name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run Backend Lint
        run: |
          cd backend
          npm run lint

      - name: Run Frontend Lint
        run: |
          cd frontend
          npx eslint "src/**/*.{js,jsx}" --config ../backend/eslint.config.mjs --fix

      - name: Run Backend Tests
        run: |
          cd backend
          npm run test

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm run test -- --config ../backend/jest.config.js

      - name: Build Project
        run: |
          cd frontend
          npm run build